### ISSUE TITLE
likely clap error

### ISSUE THREAD

**Issue by enomothem** [evilsocket/legba#29]
Win10

```
PS C:\Users\Enomothem\Desktop\legba-0.6.1> .\target\debug\legba.exe ssh --username root --password .\p.txt --target 192.168.66.132:22
legba v0.6.1

thread 'main' panicked at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\debug_asserts.rs:275:9:
Command legba: Argument group name must be unique

        'Options' is already in use
stack backtrace:
   0:     0x7ff74ae31a7a - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff74ae50f4b - core::fmt::rt::Argument::fmt
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\fmt\rt.rs:138
   2:     0x7ff74ae50f4b - core::fmt::write
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\fmt\mod.rs:1094
   3:     0x7ff74ae2d1d1 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\io\mod.rs:1714
   4:     0x7ff74ae317fa - std::sys_common::backtrace::_print
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff74ae317fa - std::sys_common::backtrace::print
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff74ae33f9a - std::panicking::default_hook::closure$1
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:270
   7:     0x7ff74ae33c08 - std::panicking::default_hook
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:290
   8:     0x7ff74ae3464e - std::panicking::rust_panic_with_hook
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:707
   9:     0x7ff74ae3453d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:599
  10:     0x7ff74ae32469 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:170
  11:     0x7ff74ae34240 - std::panicking::begin_panic_handler
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
  12:     0x7ff74ae87b75 - core::panicking::panic_fmt
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
  13:     0x7ff74adad5c9 - clap_builder::builder::debug_asserts::assert_app
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\debug_asserts.rs:275
  14:     0x7ff74ad2ea9b - clap_builder::builder::command::Command::_build_self
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\command.rs:4043
  15:     0x7ff74ad2e3a2 - clap_builder::builder::command::Command::_do_parse
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\command.rs:3914
  16:     0x7ff7490de73b - clap_builder::builder::command::Command::try_get_matches_from_mut<std::env::ArgsOs,std::ffi::os_str::OsString>
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\command.rs:791
  17:     0x7ff7490de2ae - clap_builder::builder::command::Command::get_matches_from<std::env::ArgsOs,std::ffi::os_str::OsString>
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\command.rs:662
  18:     0x7ff7490ba7a9 - clap_builder::builder::command::Command::get_matches
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\builder\command.rs:571
  19:     0x7ff7490e4651 - clap_builder::derive::Parser::parse<legba::options::Options>
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\clap_builder-4.4.7\src\derive.rs:27
  20:     0x7ff7490341fc - legba::setup
                               at C:\Users\Enomothem\Desktop\legba-0.6.1\src\main.rs:39
  21:     0x7ff748fd7737 - legba::main::async_block$0
                               at C:\Users\Enomothem\Desktop\legba-0.6.1\src\main.rs:62
  22:     0x7ff74914024f - tokio::runtime::park::impl$4::block_on::closure$0<enum2$<legba::main::async_block_env$0> >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\park.rs:282
  23:     0x7ff74913ffca - tokio::runtime::coop::with_budget
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\coop.rs:107
  24:     0x7ff74913ffca - tokio::runtime::coop::budget
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\coop.rs:73
  25:     0x7ff74913ffca - tokio::runtime::park::CachedParkThread::block_on<enum2$<legba::main::async_block_env$0> >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\park.rs:282
  26:     0x7ff749190a82 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on<enum2$<legba::main::async_block_env$0> >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\context\blocking.rs:66
  27:     0x7ff748fc1a82 - tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<enum2$<legba::main::async_block_env$0> >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\scheduler\multi_thread\mod.rs:87
  28:     0x7ff749131c6c - tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<enum2$<legba::main::async_block_env$0> >,enum2$<core::result::Result<tuple$<>,alloc::string::String> > >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\context\runtime.rs:65
  29:     0x7ff748fc1a29 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<legba::main::async_block_env$0> >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\scheduler\multi_thread\mod.rs:86
  30:     0x7ff7490338d0 - tokio::runtime::runtime::Runtime::block_on<enum2$<legba::main::async_block_env$0> >
                               at D:\bx+eno_tools\bx_eno_enviroment_rust\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tokio-1.33.0\src\runtime\runtime.rs:350
  31:     0x7ff74903518c - legba::main
                               at C:\Users\Enomothem\Desktop\legba-0.6.1\src\main.rs:91
  32:     0x7ff7491d8543 - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)(),tuple$<> >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  33:     0x7ff748f705ed - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::string::String> > (*)(),enum2$<core::result::Result<tuple$<>,alloc::string::String> > >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\sys_common\backtrace.rs:154
  34:     0x7ff7490dec36 - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,alloc::string::String> > >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\rt.rs:166
  35:     0x7ff74ae25998 - std::rt::lang_start_internal::closure$2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
  36:     0x7ff74ae25998 - std::panicking::try::do_call
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:502
  37:     0x7ff74ae25998 - std::panicking::try
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:466
  38:     0x7ff74ae25998 - std::panic::catch_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panic.rs:142
  39:     0x7ff74ae25998 - std::rt::lang_start_internal
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
  40:     0x7ff7490dec0a - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,alloc::string::String> > >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\rt.rs:165
  41:     0x7ff749035269 - main
  42:     0x7ff74ae8569c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  43:     0x7ff74ae8569c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  44:     0x7ffaf5cd7614 - BaseThreadInitThunk
  45:     0x7ffaf76e26f1 - RtlUserThreadStart
```

**Comment by evilsocket** [comment]
ref https://github.com/clap-rs/clap/discussions/4306 ... fix in progress, thanks for reporting!

**Comment by evilsocket** [comment]
fixed ... btw this happens only in debug mode. You can build with cargo build --release before I release the fix.
